DROP DATABASE IF EXISTS M6_BBDD;
CREATE DATABASE M6_BBDD;
USE M6_BBDD;

CREATE TABLE JUGADOR(
    NOMBRE VARCHAR (50) PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR (15) NOT NULL,
    PARTIDAS_GANADAS INT
) ENGINE = InnoDB;

CREATE TABLE PARTIDA(
    JUGADORES INT NOT NULL,
    ID INT NOT NULL,
    PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE ListaDePartidas(
idJuego INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
idPartida INTEGER,
FOREIGN KEY (idPartida) REFERENCES PARTIDA(id)
)ENGINE = InnoDB;

INSERT INTO JUGADOR VALUES("Pere","12D",5);
INSERT INTO JUGADOR VALUES("José","85f",10);
INSERT INTO JUGADOR VALUES("María","38F",8);
INSERT INTO JUGADOR VALUES("Marta","12gh",2);

INSERT INTO PARTIDA VALUES(1,123);
INSERT INTO PARTIDA VALUES(2,783);
INSERT INTO PARTIDA VALUES(3,859);

INSERT INTO ListaDePartidas VALUES (1, 123);
INSERT INTO ListaDePartidas VALUES (2, 783);
INSERT INTO ListaDePartidas VALUES (3, 859);